[package]
name = "arrow-typing"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow-array = "51.0.0"
arrow-buffer = "51.0.0"
arrow-schema = "51.0.0"
half = "2.4.1"

[dev-dependencies]
proptest = "1.4.0"
